"""initial schema

Revision ID: 1e3b9a4fbf7d
Revises:
Create Date: 2026-09-11 17:13:05.628532

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from migrations.views import ReplaceableView, create_view, drop_view

# revision identifiers, used by Alembic.
revision: str = "1e3b9a4fbf7d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Native Postgres enum type names. Alembic creates them with their first table
# but does not remove them when that table is dropped, so downgrade does so
# explicitly to keep downgrade/re-upgrade usable.
ENUM_TYPES = (
    "user_role",
    "oauth_issuer",
    "cashout_submission_status",
    "cashout_document_classification",
    "document_content_type",
    "ai_provider",
    "document_analysis_status",
    "tipout_department",
)


cashout_data_view = ReplaceableView(
    "reporting.cashout_data",
    select="""
        SELECT
            -- Keep these first nine columns stable: the management sheet reads
            -- them by position rather than by name.
            u.full_name                                   AS employee_name,
            to_char(s.business_date, 'YYYY-MM-DD')        AS business_date,
            d.kitchen_tipout::double precision            AS kitchen_tipout,
            d.bar_tipout::double precision                AS bar_tipout,
            d.expo_tipout::double precision               AS expo_tipout,
            d.host_tipout::double precision               AS host_tipout,
            d.cash_owed_to_house::double precision        AS cash_owed_to_house,
            d.cash_owed_to_employee::double precision     AS cash_owed_to_employee,
            row_number() OVER (ORDER BY d.created_at DESC, d.id)::integer
                                                          AS display_order,

            d.id::text                                    AS cashout_data_id,
            d.created_at                                  AS created_at,
            d.submission_id::text                         AS submission_id,
            u.id::text                                    AS employee_id,
            u.email                                       AS employee_email,
            u.role::text                                  AS employee_role,
            d.food_net_sales::double precision            AS food_net_sales,
            d.drink_net_sales::double precision           AS drink_net_sales,
            d.total_net_sales::double precision           AS total_net_sales,
            d.card_payment_total::double precision        AS card_payment_total,
            d.cash_payment_total::double precision        AS cash_payment_total,
            d.card_tip_total::double precision            AS card_tip_total,
            array_to_string(d.tipout_departments, ', ')   AS tipout_departments,
            d.bar_tipout_rate::double precision           AS bar_tipout_rate,
            d.kitchen_tipout_rate::double precision       AS kitchen_tipout_rate,
            d.expo_tipout_rate::double precision          AS expo_tipout_rate,
            d.host_tipout_rate::double precision          AS host_tipout_rate,
            d.manager_tipout::double precision            AS manager_tipout,
            d.manager_tipout_rate::double precision       AS manager_tipout_rate,
            d.deposit_total::double precision             AS deposit_total,
            d.adjustment_note                             AS adjustment_note
        FROM public.cashout_data AS d
        JOIN public.cashout_submissions AS s ON s.id = d.submission_id
        JOIN public.users AS u ON u.id = s.employee_user_id
        ORDER BY d.created_at DESC, d.id
    """,
    after_create=(
        """
        COMMENT ON VIEW reporting.cashout_data IS
            'The admin "Cashout data" table (GET /api/cashout/data): one row per'
            ' reconciled cashout, newest first. The first nine columns feed the'
            ' management Google Sheet by position; the rest are the remainder of'
            ' the API row, with the manager tipout and its rate, then the'
            ' reconciliation adjustment (deposit and note), appended last.'
        """,
        "GRANT SELECT ON reporting.cashout_data TO reporting_reader",
    ),
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox_messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("type", sa.String(length=200), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("claim_id", sa.Uuid(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "attempts", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("max_attempts", sa.Integer(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dead_lettered_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_outbox_messages_pending",
        "outbox_messages",
        ["available_at", "created_at"],
        unique=False,
        postgresql_where=sa.text("completed_at IS NULL AND dead_lettered_at IS NULL"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("staff", "admin", "owner", name="user_role"),
            server_default="staff",
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.create_index(
        "ix_users_single_owner",
        "users",
        ["role"],
        unique=True,
        postgresql_where=sa.text("role = 'owner'"),
    )
    op.create_table(
        "cashout_submissions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("processing", "completed", name="cashout_submission_status"),
            server_default="processing",
            nullable=False,
        ),
        sa.Column("employee_user_id", sa.Uuid(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("business_date", sa.Date(), nullable=False),
        sa.Column("completed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("first_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "tipout_departments",
            sa.ARRAY(
                sa.Enum(
                    "bar",
                    "kitchen",
                    "expo",
                    "host",
                    "manager",
                    name="tipout_department",
                )
            ),
            nullable=True,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["completed_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employee_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cashout_submissions_business_date"),
        "cashout_submissions",
        ["business_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cashout_submissions_completed_by_user_id"),
        "cashout_submissions",
        ["completed_by_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_cashout_submissions_employee_business_date",
        "cashout_submissions",
        ["employee_user_id", "business_date"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        op.f("ix_cashout_submissions_employee_user_id"),
        "cashout_submissions",
        ["employee_user_id"],
        unique=False,
    )
    op.create_table(
        "external_identities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("issuer", sa.Enum("google", name="oauth_issuer"), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_external_identities_issuer_subject",
        "external_identities",
        ["issuer", "subject"],
        unique=True,
    )
    op.create_index(
        "ix_external_identities_user_issuer",
        "external_identities",
        ["user_id", "issuer"],
        unique=True,
    )
    op.create_table(
        "cashout_data",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("food_net_sales", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("drink_net_sales", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total_net_sales", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "card_payment_total", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column(
            "cash_payment_total", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column("card_tip_total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("deposit_total", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("adjustment_note", sa.Text(), nullable=True),
        sa.Column(
            "tipout_departments",
            sa.ARRAY(
                sa.Enum(
                    "bar",
                    "kitchen",
                    "expo",
                    "host",
                    "manager",
                    name="tipout_department",
                )
            ),
            nullable=False,
        ),
        sa.Column(
            "bar_tipout",
            sa.Numeric(precision=12, scale=2),
            sa.Computed(
                "\n            CASE\n                WHEN 'bar'::tipout_department = ANY(tipout_departments)\n                THEN (ceil((drink_net_sales * bar_tipout_rate) * 100) / 100)\n                ELSE NULL\n            END\n        ",
            ),
            nullable=True,
        ),
        sa.Column(
            "kitchen_tipout",
            sa.Numeric(precision=12, scale=2),
            sa.Computed(
                "\n            CASE\n                WHEN 'kitchen'::tipout_department = ANY(tipout_departments)\n                THEN (ceil((food_net_sales * kitchen_tipout_rate) * 100) / 100)\n                ELSE NULL\n            END\n        ",
            ),
            nullable=True,
        ),
        sa.Column(
            "expo_tipout",
            sa.Numeric(precision=12, scale=2),
            sa.Computed(
                "\n            CASE\n                WHEN 'expo'::tipout_department = ANY(tipout_departments)\n                THEN (ceil((food_net_sales * expo_tipout_rate) * 100) / 100)\n                ELSE NULL\n            END\n        ",
            ),
            nullable=True,
        ),
        sa.Column(
            "host_tipout",
            sa.Numeric(precision=12, scale=2),
            sa.Computed(
                "\n            CASE\n                WHEN 'host'::tipout_department = ANY(tipout_departments)\n                THEN (ceil((total_net_sales * host_tipout_rate) * 100) / 100)\n                ELSE NULL\n            END\n        ",
            ),
            nullable=True,
        ),
        sa.Column(
            "manager_tipout",
            sa.Numeric(precision=12, scale=2),
            sa.Computed(
                "\n            CASE\n                WHEN 'manager'::tipout_department = ANY(tipout_departments)\n                THEN (ceil((total_net_sales * manager_tipout_rate) * 100) / 100)\n                ELSE NULL\n            END\n        ",
            ),
            nullable=True,
        ),
        sa.Column(
            "cash_owed_to_house",
            sa.Numeric(precision=12, scale=2),
            sa.Computed(
                "\n            CASE\n                WHEN (ceil((\n    (cash_payment_total - card_tip_total + \n    (\n        CASE\n            WHEN 'bar'::tipout_department = ANY(tipout_departments)\n            THEN (ceil((drink_net_sales * bar_tipout_rate) * 100) / 100)\n            ELSE 0\n        END\n        + CASE\n            WHEN 'kitchen'::tipout_department = ANY(tipout_departments)\n            THEN (ceil((food_net_sales * kitchen_tipout_rate) * 100) / 100)\n            ELSE 0\n        END\n        + CASE\n            WHEN 'expo'::tipout_department = ANY(tipout_departments)\n            THEN (ceil((food_net_sales * expo_tipout_rate) * 100) / 100)\n            ELSE 0\n        END\n        + CASE\n            WHEN 'host'::tipout_department = ANY(tipout_departments)\n            THEN (ceil((total_net_sales * host_tipout_rate) * 100) / 100)\n            ELSE 0\n        END\n        + CASE\n            WHEN 'manager'::tipout_department = ANY(tipout_departments)\n            THEN (ceil((total_net_sales * manager_tipout_rate) * 100) / 100)\n            ELSE 0\n        END\n    )\n)\n) * 100) / 100) > 0\n                THEN (ceil((\n    (cash_payment_total - card_tip_total + \n    (\n        CASE\n            WHEN 'bar'::tipout_department = ANY(tipout_departments)\n            THEN (ceil((drink_net_sales * bar_tipout_rate) * 100) / 100)\n            ELSE 0\n        END\n        + CASE\n            WHEN 'kitchen'::tipout_department = ANY(tipout_departments)\n            THEN (ceil((food_net_sales * kitchen_tipout_rate) * 100) / 100)\n            ELSE 0\n        END\n        + CASE\n            WHEN 'expo'::tipout_department = ANY(tipout_departments)\n            THEN (ceil((food_net_sales * expo_tipout_rate) * 100) / 100)\n            ELSE 0\n        END\n        + CASE\n            WHEN 'host'::tipout_department = ANY(tipout_departments)\n            THEN (ceil((total_net_sales * host_tipout_rate) * 100) / 100)\n            ELSE 0\n        END\n        + CASE\n            WHEN 'manager'::tipout_department = ANY(tipout_departments)\n            THEN (ceil((total_net_sales * manager_tipout_rate) * 100) / 100)\n            ELSE 0\n        END\n    )\n)\n) * 100) / 100)\n                ELSE NULL\n            END\n        ",
            ),
            nullable=True,
        ),
        sa.Column(
            "cash_owed_to_employee",
            sa.Numeric(precision=12, scale=2),
            sa.Computed(
                "\n            CASE\n                WHEN (ceil((\n    (cash_payment_total - card_tip_total + \n    (\n        CASE\n            WHEN 'bar'::tipout_department = ANY(tipout_departments)\n            THEN (ceil((drink_net_sales * bar_tipout_rate) * 100) / 100)\n            ELSE 0\n        END\n        + CASE\n            WHEN 'kitchen'::tipout_department = ANY(tipout_departments)\n            THEN (ceil((food_net_sales * kitchen_tipout_rate) * 100) / 100)\n            ELSE 0\n        END\n        + CASE\n            WHEN 'expo'::tipout_department = ANY(tipout_departments)\n            THEN (ceil((food_net_sales * expo_tipout_rate) * 100) / 100)\n            ELSE 0\n        END\n        + CASE\n            WHEN 'host'::tipout_department = ANY(tipout_departments)\n            THEN (ceil((total_net_sales * host_tipout_rate) * 100) / 100)\n            ELSE 0\n        END\n        + CASE\n            WHEN 'manager'::tipout_department = ANY(tipout_departments)\n            THEN (ceil((total_net_sales * manager_tipout_rate) * 100) / 100)\n            ELSE 0\n        END\n    )\n)\n) * 100) / 100) < 0\n                THEN -(ceil((\n    (cash_payment_total - card_tip_total + \n    (\n        CASE\n            WHEN 'bar'::tipout_department = ANY(tipout_departments)\n            THEN (ceil((drink_net_sales * bar_tipout_rate) * 100) / 100)\n            ELSE 0\n        END\n        + CASE\n            WHEN 'kitchen'::tipout_department = ANY(tipout_departments)\n            THEN (ceil((food_net_sales * kitchen_tipout_rate) * 100) / 100)\n            ELSE 0\n        END\n        + CASE\n            WHEN 'expo'::tipout_department = ANY(tipout_departments)\n            THEN (ceil((food_net_sales * expo_tipout_rate) * 100) / 100)\n            ELSE 0\n        END\n        + CASE\n            WHEN 'host'::tipout_department = ANY(tipout_departments)\n            THEN (ceil((total_net_sales * host_tipout_rate) * 100) / 100)\n            ELSE 0\n        END\n        + CASE\n            WHEN 'manager'::tipout_department = ANY(tipout_departments)\n            THEN (ceil((total_net_sales * manager_tipout_rate) * 100) / 100)\n            ELSE 0\n        END\n    )\n)\n) * 100) / 100)\n                ELSE NULL\n            END\n        ",
            ),
            nullable=True,
        ),
        sa.Column("bar_tipout_rate", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column(
            "kitchen_tipout_rate", sa.Numeric(precision=6, scale=4), nullable=False
        ),
        sa.Column("expo_tipout_rate", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("host_tipout_rate", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column(
            "manager_tipout_rate", sa.Numeric(precision=6, scale=4), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["cashout_submissions.id"],
            name="cashout_data_submission_id_fkey",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cashout_data_submission_id"),
        "cashout_data",
        ["submission_id"],
        unique=True,
    )
    op.create_table(
        "cashout_uploads",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("cashout_submission_id", sa.Uuid(), nullable=False),
        sa.Column(
            "content_type",
            sa.Enum(
                "image/jpeg",
                "image/png",
                "image/webp",
                "application/pdf",
                name="document_content_type",
            ),
            nullable=False,
        ),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("uploaded_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cashout_submission_id"], ["cashout_submissions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index(
        op.f("ix_cashout_uploads_cashout_submission_id"),
        "cashout_uploads",
        ["cashout_submission_id"],
        unique=False,
    )
    op.create_index(
        "ix_cashout_uploads_submission_checksum",
        "cashout_uploads",
        ["cashout_submission_id", "checksum_sha256"],
        unique=True,
    )
    op.create_index(
        op.f("ix_cashout_uploads_uploaded_by_user_id"),
        "cashout_uploads",
        ["uploaded_by_user_id"],
        unique=False,
    )
    op.create_table(
        "cashout_document_analyses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("cashout_upload_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "provider",
            sa.Enum("anthropic", "openai", "gemini", name="ai_provider"),
            nullable=True,
        ),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "extracting",
                "needs_verification",
                "verified",
                "failed",
                name="document_analysis_status",
            ),
            server_default="extracting",
            nullable=False,
        ),
        sa.Column(
            "classification",
            sa.Enum(
                "touchbistro_report",
                "server_summary_report",
                "gift_certificate",
                name="cashout_document_classification",
            ),
            nullable=True,
        ),
        sa.Column("classification_confidence", sa.Float(), nullable=True),
        sa.Column("schema_name", sa.String(length=100), nullable=True),
        sa.Column("schema_version", sa.Integer(), nullable=True),
        sa.Column(
            "extracted_data_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("extraction_confidence", sa.Float(), nullable=True),
        sa.Column("issues", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("cropped_storage_key", sa.String(length=512), nullable=True),
        sa.Column(
            "cropped_content_type",
            sa.Enum(
                "image/jpeg",
                "image/png",
                "image/webp",
                "application/pdf",
                name="document_content_type",
            ),
            nullable=True,
        ),
        sa.Column(
            "crop_bounds", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "verified_data_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("verified_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["cashout_upload_id"], ["cashout_uploads.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["verified_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "cashout_upload_id",
            "position",
            name="uq_cashout_document_analyses_upload_position",
        ),
        sa.UniqueConstraint("cropped_storage_key"),
    )
    op.create_index(
        op.f("ix_cashout_document_analyses_cashout_upload_id"),
        "cashout_document_analyses",
        ["cashout_upload_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cashout_document_analyses_verified_by_user_id"),
        "cashout_document_analyses",
        ["verified_by_user_id"],
        unique=False,
    )

    op.execute("CREATE SCHEMA reporting")
    op.execute(
        "COMMENT ON SCHEMA reporting IS 'Read-only reporting views for spreadsheet"
        " consumers (the management Google Sheet).'"
    )

    # Roles are cluster-wide, so a role retained by a downgrade or shared by
    # another database on the same server may already exist.
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'reporting_reader') THEN
                CREATE ROLE reporting_reader NOLOGIN;
            END IF;
        END
        $$
        """
    )
    op.execute("GRANT USAGE ON SCHEMA reporting TO reporting_reader")
    create_view(cashout_data_view)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    drop_view(cashout_data_view)
    op.execute("DROP SCHEMA reporting")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_cashout_document_analyses_verified_by_user_id"),
        table_name="cashout_document_analyses",
    )
    op.drop_index(
        op.f("ix_cashout_document_analyses_cashout_upload_id"),
        table_name="cashout_document_analyses",
    )
    op.drop_table("cashout_document_analyses")
    op.drop_index(
        op.f("ix_cashout_uploads_uploaded_by_user_id"), table_name="cashout_uploads"
    )
    op.drop_index(
        "ix_cashout_uploads_submission_checksum", table_name="cashout_uploads"
    )
    op.drop_index(
        op.f("ix_cashout_uploads_cashout_submission_id"), table_name="cashout_uploads"
    )
    op.drop_table("cashout_uploads")
    op.drop_index(op.f("ix_cashout_data_submission_id"), table_name="cashout_data")
    op.drop_table("cashout_data")
    op.drop_index(
        "ix_external_identities_user_issuer", table_name="external_identities"
    )
    op.drop_index(
        "ix_external_identities_issuer_subject", table_name="external_identities"
    )
    op.drop_table("external_identities")
    op.drop_index(
        op.f("ix_cashout_submissions_employee_user_id"),
        table_name="cashout_submissions",
    )
    op.drop_index(
        "ix_cashout_submissions_employee_business_date",
        table_name="cashout_submissions",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        op.f("ix_cashout_submissions_completed_by_user_id"),
        table_name="cashout_submissions",
    )
    op.drop_index(
        op.f("ix_cashout_submissions_business_date"), table_name="cashout_submissions"
    )
    op.drop_table("cashout_submissions")
    op.drop_index(
        "ix_users_single_owner",
        table_name="users",
        postgresql_where=sa.text("role = 'owner'"),
    )
    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")
    op.drop_index(
        "ix_outbox_messages_pending",
        table_name="outbox_messages",
        postgresql_where=sa.text("completed_at IS NULL AND dead_lettered_at IS NULL"),
    )
    op.drop_table("outbox_messages")
    # ### end Alembic commands ###

    for enum_name in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
