"""Add unique index on cashout document submission and checksum

Revision ID: 6c4e4b01629d
Revises: cbf386fc33b2
Create Date: 2026-07-18 23:09:34.206099

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6c4e4b01629d"
down_revision: Union[str, Sequence[str], None] = "cbf386fc33b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_cashout_documents_submission_checksum",
        "cashout_documents",
        ["cashout_submission_id", "checksum_sha256"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_cashout_documents_submission_checksum", table_name="cashout_documents"
    )
    # ### end Alembic commands ###
