"""initial schema

Revision ID: cbf386fc33b2
Revises:
Create Date: 2026-07-16 23:10:49.031736

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cbf386fc33b2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Native Postgres enum type names, kept in sync with the enum_column() calls on
# the models. Autogenerate creates these types but never drops them, so we drop
# them explicitly on downgrade — otherwise a re-upgrade fails with "type already
# exists".
ENUM_TYPES = (
    "user_role",
    "cashout_submission_status",
    "cashout_document_classification",
    "document_content_type",
    "ai_provider",
    "document_analysis_status",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("CASHIER", "ADMIN", name="user_role"),
            server_default="CASHIER",
            nullable=False,
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "cashout_submissions",
        sa.Column(
            "status",
            sa.Enum("PROCESSING", "COMPLETED", name="cashout_submission_status"),
            server_default="PROCESSING",
            nullable=False,
        ),
        sa.Column("submitted_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cashout_submissions_submitted_by_user_id"),
        "cashout_submissions",
        ["submitted_by_user_id"],
        unique=False,
    )
    op.create_table(
        "sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sessions_token_hash"), "sessions", ["token_hash"], unique=True
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "cashout_data",
        sa.Column("daily_tipout", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("net_total", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("cash_total", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("card_total", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"], ["cashout_submissions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cashout_data_submission_id"),
        "cashout_data",
        ["submission_id"],
        unique=True,
    )
    op.create_table(
        "cashout_documents",
        sa.Column(
            "content_type",
            sa.Enum(
                "image/jpeg",
                "image/png",
                "image/webp",
                "application/pdf",
                name="document_content_type",
            ),
            nullable=False,
        ),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("uploaded_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cashout_submission_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cashout_submission_id"], ["cashout_submissions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index(
        op.f("ix_cashout_documents_cashout_submission_id"),
        "cashout_documents",
        ["cashout_submission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cashout_documents_uploaded_by_user_id"),
        "cashout_documents",
        ["uploaded_by_user_id"],
        unique=False,
    )
    op.create_table(
        "cashout_document_analyses",
        sa.Column(
            "provider",
            sa.Enum("ANTHROPIC", "OPENAI", "GEMINI", name="ai_provider"),
            nullable=False,
        ),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "EXTRACTING",
                "NEEDS_VERIFICATION",
                "VERIFIED",
                "FAILED",
                name="document_analysis_status",
            ),
            server_default="EXTRACTING",
            nullable=False,
        ),
        sa.Column(
            "classification",
            sa.Enum(
                "TOUCHBISTRO_SERVER_SHIFT_REPORT",
                "PAYSTONE_TERMINAL_REPORT",
                "PAYMENT_RECEIPT",
                "DAILY_TIP_OUT_SHEET",
                "DAILY_CASH_SUMMARY",
                "MANUAL_NOTE",
                name="cashout_document_classification",
            ),
            nullable=True,
        ),
        sa.Column("classification_confidence", sa.Float(), nullable=True),
        sa.Column("schema_name", sa.String(length=100), nullable=True),
        sa.Column(
            "extracted_data_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("extraction_confidence", sa.Float(), nullable=True),
        sa.Column("issues", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "verified_data_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("verified_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cashout_document_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cashout_document_id"], ["cashout_documents.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["verified_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cashout_document_analyses_cashout_document_id"),
        "cashout_document_analyses",
        ["cashout_document_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_cashout_document_analyses_verified_by_user_id"),
        "cashout_document_analyses",
        ["verified_by_user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_cashout_document_analyses_verified_by_user_id"),
        table_name="cashout_document_analyses",
    )
    op.drop_index(
        op.f("ix_cashout_document_analyses_cashout_document_id"),
        table_name="cashout_document_analyses",
    )
    op.drop_table("cashout_document_analyses")
    op.drop_index(
        op.f("ix_cashout_documents_uploaded_by_user_id"), table_name="cashout_documents"
    )
    op.drop_index(
        op.f("ix_cashout_documents_cashout_submission_id"),
        table_name="cashout_documents",
    )
    op.drop_table("cashout_documents")
    op.drop_index(op.f("ix_cashout_data_submission_id"), table_name="cashout_data")
    op.drop_table("cashout_data")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_token_hash"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(
        op.f("ix_cashout_submissions_submitted_by_user_id"),
        table_name="cashout_submissions",
    )
    op.drop_table("cashout_submissions")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###

    for enum_name in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
