"""initial schema

Revision ID: f6c0323b07d2
Revises:
Create Date: 2026-08-29 04:08:37.144792

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f6c0323b07d2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Native Postgres enum type names, kept in sync with the enum_column() calls on
# the models. Autogenerate creates these types but never drops them, so we drop
# them explicitly on downgrade — otherwise a re-upgrade fails with "type already
# exists".
ENUM_TYPES = (
    "user_role",
    "oauth_issuer",
    "cashout_submission_status",
    "cashout_document_classification",
    "document_content_type",
    "ai_provider",
    "document_analysis_status",
    "tipout_department",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox_messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("type", sa.String(length=200), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("claim_id", sa.Uuid(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "attempts", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("max_attempts", sa.Integer(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dead_lettered_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_outbox_messages_pending",
        "outbox_messages",
        ["available_at", "created_at"],
        unique=False,
        postgresql_where=sa.text("completed_at IS NULL AND dead_lettered_at IS NULL"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("staff", "admin", "owner", name="user_role"),
            server_default="staff",
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.create_index(
        "ix_users_single_owner",
        "users",
        ["role"],
        unique=True,
        postgresql_where=sa.text("role = 'owner'"),
    )
    op.create_table(
        "cashout_submissions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("processing", "completed", name="cashout_submission_status"),
            server_default="processing",
            nullable=False,
        ),
        sa.Column("employee_user_id", sa.Uuid(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("first_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "tipout_departments",
            sa.ARRAY(
                sa.Enum("bar", "kitchen", "expo", "host", name="tipout_department")
            ),
            nullable=True,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["completed_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employee_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cashout_submissions_completed_by_user_id"),
        "cashout_submissions",
        ["completed_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cashout_submissions_employee_user_id"),
        "cashout_submissions",
        ["employee_user_id"],
        unique=False,
    )
    op.create_table(
        "external_identities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("issuer", sa.Enum("google", name="oauth_issuer"), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_external_identities_issuer_subject",
        "external_identities",
        ["issuer", "subject"],
        unique=True,
    )
    op.create_index(
        "ix_external_identities_user_issuer",
        "external_identities",
        ["user_id", "issuer"],
        unique=True,
    )
    op.create_table(
        "cashout_data",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("food_net_sales", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("drink_net_sales", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("total_net_sales", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "card_payment_total", sa.Numeric(precision=12, scale=2), nullable=True
        ),
        sa.Column(
            "cash_payment_total", sa.Numeric(precision=12, scale=2), nullable=True
        ),
        sa.Column("card_tip_total", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "tipout_departments",
            sa.ARRAY(
                sa.Enum("bar", "kitchen", "expo", "host", name="tipout_department")
            ),
            nullable=False,
        ),
        sa.Column(
            "bar_tipout",
            sa.Numeric(precision=12, scale=2),
            sa.Computed(
                "\n            CASE\n                WHEN 'bar'::tipout_department = ANY(tipout_departments)\n                THEN drink_net_sales * bar_tipout_rate\n                ELSE NULL\n            END\n        ",
            ),
            nullable=True,
        ),
        sa.Column(
            "kitchen_tipout",
            sa.Numeric(precision=12, scale=2),
            sa.Computed(
                "\n            CASE\n                WHEN 'kitchen'::tipout_department = ANY(tipout_departments)\n                THEN food_net_sales * kitchen_tipout_rate\n                ELSE NULL\n            END\n        ",
            ),
            nullable=True,
        ),
        sa.Column(
            "expo_tipout",
            sa.Numeric(precision=12, scale=2),
            sa.Computed(
                "\n            CASE\n                WHEN 'expo'::tipout_department = ANY(tipout_departments)\n                THEN total_net_sales * expo_tipout_rate\n                ELSE NULL\n            END\n        ",
            ),
            nullable=True,
        ),
        sa.Column(
            "host_tipout",
            sa.Numeric(precision=12, scale=2),
            sa.Computed(
                "\n            CASE\n                WHEN 'host'::tipout_department = ANY(tipout_departments)\n                THEN total_net_sales * host_tipout_rate\n                ELSE NULL\n            END\n        ",
            ),
            nullable=True,
        ),
        sa.Column(
            "cash_owed_to_house",
            sa.Numeric(precision=12, scale=2),
            sa.Computed(
                "\n            CASE\n                WHEN cash_payment_total > card_tip_total\n                THEN cash_payment_total - card_tip_total\n                ELSE NULL\n            END\n        ",
            ),
            nullable=True,
        ),
        sa.Column(
            "cash_owed_to_employee",
            sa.Numeric(precision=12, scale=2),
            sa.Computed(
                "\n            CASE\n                WHEN card_tip_total > cash_payment_total\n                THEN card_tip_total - cash_payment_total\n                ELSE NULL\n            END\n        ",
            ),
            nullable=True,
        ),
        sa.Column("bar_tipout_rate", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column(
            "kitchen_tipout_rate", sa.Numeric(precision=6, scale=4), nullable=False
        ),
        sa.Column("expo_tipout_rate", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("host_tipout_rate", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["cashout_submissions.id"],
            name="cashout_data_submission_id_fkey",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cashout_data_submission_id"),
        "cashout_data",
        ["submission_id"],
        unique=True,
    )
    op.create_table(
        "cashout_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("cashout_submission_id", sa.Uuid(), nullable=False),
        sa.Column(
            "content_type",
            sa.Enum(
                "image/jpeg",
                "image/png",
                "image/webp",
                "application/pdf",
                name="document_content_type",
            ),
            nullable=False,
        ),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("uploaded_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cashout_submission_id"], ["cashout_submissions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index(
        op.f("ix_cashout_documents_cashout_submission_id"),
        "cashout_documents",
        ["cashout_submission_id"],
        unique=False,
    )
    op.create_index(
        "ix_cashout_documents_submission_checksum",
        "cashout_documents",
        ["cashout_submission_id", "checksum_sha256"],
        unique=True,
    )
    op.create_index(
        op.f("ix_cashout_documents_uploaded_by_user_id"),
        "cashout_documents",
        ["uploaded_by_user_id"],
        unique=False,
    )
    op.create_table(
        "cashout_document_analyses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("cashout_document_id", sa.Uuid(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum("anthropic", "openai", "gemini", name="ai_provider"),
            nullable=True,
        ),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "extracting",
                "needs_verification",
                "verified",
                "failed",
                name="document_analysis_status",
            ),
            server_default="extracting",
            nullable=False,
        ),
        sa.Column(
            "classification",
            sa.Enum(
                "touchbistro_report",
                "server_summary_report",
                "unknown",
                name="cashout_document_classification",
            ),
            nullable=True,
        ),
        sa.Column("classification_confidence", sa.Float(), nullable=True),
        sa.Column("schema_name", sa.String(length=100), nullable=True),
        sa.Column(
            "extracted_data_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("extraction_confidence", sa.Float(), nullable=True),
        sa.Column("issues", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "verified_data_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("verified_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["cashout_document_id"], ["cashout_documents.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["verified_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cashout_document_analyses_cashout_document_id"),
        "cashout_document_analyses",
        ["cashout_document_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_cashout_document_analyses_verified_by_user_id"),
        "cashout_document_analyses",
        ["verified_by_user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_cashout_document_analyses_verified_by_user_id"),
        table_name="cashout_document_analyses",
    )
    op.drop_index(
        op.f("ix_cashout_document_analyses_cashout_document_id"),
        table_name="cashout_document_analyses",
    )
    op.drop_table("cashout_document_analyses")
    op.drop_index(
        op.f("ix_cashout_documents_uploaded_by_user_id"), table_name="cashout_documents"
    )
    op.drop_index(
        "ix_cashout_documents_submission_checksum", table_name="cashout_documents"
    )
    op.drop_index(
        op.f("ix_cashout_documents_cashout_submission_id"),
        table_name="cashout_documents",
    )
    op.drop_table("cashout_documents")
    op.drop_index(op.f("ix_cashout_data_submission_id"), table_name="cashout_data")
    op.drop_table("cashout_data")
    op.drop_index(
        "ix_external_identities_user_issuer", table_name="external_identities"
    )
    op.drop_index(
        "ix_external_identities_issuer_subject", table_name="external_identities"
    )
    op.drop_table("external_identities")
    op.drop_index(
        op.f("ix_cashout_submissions_employee_user_id"),
        table_name="cashout_submissions",
    )
    op.drop_index(
        op.f("ix_cashout_submissions_completed_by_user_id"),
        table_name="cashout_submissions",
    )
    op.drop_table("cashout_submissions")
    op.drop_index(
        "ix_users_single_owner",
        table_name="users",
        postgresql_where=sa.text("role = 'owner'"),
    )
    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")
    op.drop_index(
        "ix_outbox_messages_pending",
        table_name="outbox_messages",
        postgresql_where=sa.text("completed_at IS NULL AND dead_lettered_at IS NULL"),
    )
    op.drop_table("outbox_messages")
    # ### end Alembic commands ###

    for enum_name in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
